# Generated by Django 5.0.8 on 2026-02-15 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role', models.TextField(blank=True, default='')),
                ('goal', models.TextField(blank=True, default='')),
                ('action_type', models.CharField(default='custom', max_length=80)),
                ('schedule_cron', models.CharField(blank=True, default='', max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('sandbox', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groq_api_key', models.TextField(blank=True, default='')),
                ('groq_model', models.CharField(default='llama-3.3-70b-versatile', max_length=120)),
                ('sandbox_default', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=80)),
                ('level', models.CharField(default='info', max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RunLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'success'), ('failed', 'failed'), ('sandboxed', 'sandboxed')], default='success', max_length=20)),
                ('message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField()),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='runs', to='app.agent')),
            ],
        ),
    ]
